import { Ionicons } from "@expo/vector-icons";
import {
    endOfMonth,
    endOfYear,
    format,
    startOfMonth,
    startOfYear,
    subMonths,
    subYears,
} from "date-fns";
import { File, Paths } from "expo-file-system";
import * as Sharing from "expo-sharing";
import React, { useMemo, useState } from "react";
import {
    Alert,
    ScrollView,
    StyleSheet,
    Text,
    TouchableOpacity,
    View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { AnimatedNumber } from "../src/components/atoms/AnimatedNumber";
import { Card } from "../src/components/atoms/Card";
import { Icon } from "../src/components/atoms/Icon";
import { useAppSelector } from "../src/hooks/useRedux";
import { useThemeColors } from "../src/hooks/useThemeColors";
import { spacing, typography } from "../src/theme/theme";
import {
    calculateCategoryBreakdown,
    calculateTotalIncome,
    calculateTotalSpent,
    filterExpensesByDateRange,
    getCategoryBudgetStatus,
} from "../src/utils/calculations";
import { formatCurrency } from "../src/utils/formatters";

type ReportPeriod = "month" | "year";

export default function ReportsScreen() {
  const expenses = useAppSelector((state) => state.expenses.expenses);
  const incomes = useAppSelector((state) => state.incomes.incomes);
  const budgets = useAppSelector((state) => state.budgets.budgets);
  const categories = useAppSelector((state) => state.categories.categories);
  const savingsGoals = useAppSelector((state) => state.savings.goals);
  const currency = useAppSelector((state) => state.settings.currency);
  const colors = useThemeColors();

  const [period, setPeriod] = useState<ReportPeriod>("month");
  const [offset, setOffset] = useState(0); // 0 = current, 1 = previous, etc.

  const { currentStart, currentEnd, prevStart, prevEnd, periodLabel } =
    useMemo(() => {
      const now = new Date();
      if (period === "month") {
        const ref = subMonths(now, offset);
        return {
          currentStart: startOfMonth(ref),
          currentEnd: endOfMonth(ref),
          prevStart: startOfMonth(subMonths(ref, 1)),
          prevEnd: endOfMonth(subMonths(ref, 1)),
          periodLabel: format(ref, "MMMM yyyy"),
        };
      }
      const ref = subYears(now, offset);
      return {
        currentStart: startOfYear(ref),
        currentEnd: endOfYear(ref),
        prevStart: startOfYear(subYears(ref, 1)),
        prevEnd: endOfYear(subYears(ref, 1)),
        periodLabel: format(ref, "yyyy"),
      };
    }, [period, offset]);

  const filterIncomes = (start: Date, end: Date) =>
    incomes.filter((i) => {
      const d = new Date(i.date);
      return d >= start && d <= end;
    });

  const curExpenses = filterExpensesByDateRange(
    expenses,
    currentStart,
    currentEnd,
  );
  const curIncomes = filterIncomes(currentStart, currentEnd);
  const prevExpenses = filterExpensesByDateRange(expenses, prevStart, prevEnd);
  const prevIncomes = filterIncomes(prevStart, prevEnd);

  const curSpent = calculateTotalSpent(curExpenses);
  const curIncome = calculateTotalIncome(curIncomes);
  const curBalance = curIncome - curSpent;
  const prevSpent = calculateTotalSpent(prevExpenses);
  const prevIncome = calculateTotalIncome(prevIncomes);
  const prevBalance = prevIncome - prevSpent;

  const spentChange =
    prevSpent > 0 ? ((curSpent - prevSpent) / prevSpent) * 100 : 0;
  const incomeChange =
    prevIncome > 0 ? ((curIncome - prevIncome) / prevIncome) * 100 : 0;

  const curBreakdown = calculateCategoryBreakdown(curExpenses, categories);
  const prevBreakdown = calculateCategoryBreakdown(prevExpenses, categories);

  const budgetStatuses = getCategoryBudgetStatus(budgets, expenses, categories);
  const overBudgetCount = budgetStatuses.filter((b) => b.isOverBudget).length;

  const savingsTotal = savingsGoals.reduce((s, g) => s + g.currentAmount, 0);
  const savingsTarget = savingsGoals.reduce((s, g) => s + g.targetAmount, 0);

  const handleShareReport = async () => {
    const topCategories = curBreakdown
      .slice(0, 5)
      .map(
        (c) => `  • ${c.category.name}: ${formatCurrency(c.amount, currency)}`,
      )
      .join("\n");
    const text = [
      `📊 SpendWise Report — ${periodLabel}`,
      ``,
      `Income:    ${formatCurrency(curIncome, currency)}`,
      `Expenses:  ${formatCurrency(curSpent, currency)}`,
      `Balance:   ${formatCurrency(curBalance, currency)}`,
      ``,
      `Top Categories:`,
      topCategories || "  No data",
      ``,
      `Budgets over limit: ${overBudgetCount}`,
      savingsTarget > 0
        ? `Savings progress: ${formatCurrency(savingsTotal, currency)} / ${formatCurrency(savingsTarget, currency)}`
        : "",
      ``,
      `Generated by SpendWise`,
    ]
      .filter((l) => l !== undefined)
      .join("\n");

    try {
      const canShare = await Sharing.isAvailableAsync();
      if (!canShare) {
        Alert.alert("Sharing not available on this device");
        return;
      }
      // Write to a temp .txt file then share
      const file = new File(
        Paths.cache,
        `spendwise_report_${periodLabel.replace(/\s/g, "_")}.txt`,
      );
      file.write(text);
      await Sharing.shareAsync(file.uri, {
        mimeType: "text/plain",
        dialogTitle: `SpendWise Report — ${periodLabel}`,
      });
    } catch {
      Alert.alert("Export failed", "Could not share the report.");
    }
  };

  const ChangeIndicator = ({
    value,
    inverted = false,
  }: {
    value: number;
    inverted?: boolean;
  }) => {
    const isGood = inverted ? value < 0 : value > 0;
    const isNeutral = Math.abs(value) < 1;
    return (
      <View
        style={[
          styles.changeBadge,
          {
            backgroundColor: isNeutral
              ? colors.border
              : isGood
                ? colors.success + "15"
                : colors.error + "15",
          },
        ]}
      >
        <Ionicons
          name={value > 0 ? "arrow-up" : value < 0 ? "arrow-down" : "remove"}
          size={12}
          color={
            isNeutral
              ? colors.textLight
              : isGood
                ? colors.success
                : colors.error
          }
        />
        <Text
          style={{
            fontSize: 11,
            fontWeight: "600",
            color: isNeutral
              ? colors.textLight
              : isGood
                ? colors.success
                : colors.error,
          }}
        >
          {Math.abs(value).toFixed(1)}%
        </Text>
      </View>
    );
  };

  return (
    <SafeAreaView
      style={[styles.container, { backgroundColor: colors.background }]}
      edges={["bottom"]}
    >
      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        {/* Period Toggle */}
        <View style={styles.periodRow}>
          <TouchableOpacity
            style={[
              styles.periodBtn,
              period === "month" && { backgroundColor: colors.primary },
              period !== "month" && {
                backgroundColor: colors.card,
                borderColor: colors.border,
                borderWidth: 1,
              },
            ]}
            onPress={() => {
              setPeriod("month");
              setOffset(0);
            }}
          >
            <Text
              style={{
                color: period === "month" ? "#FFF" : colors.text,
                fontWeight: "600",
              }}
            >
              Monthly
            </Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[
              styles.periodBtn,
              period === "year" && { backgroundColor: colors.primary },
              period !== "year" && {
                backgroundColor: colors.card,
                borderColor: colors.border,
                borderWidth: 1,
              },
            ]}
            onPress={() => {
              setPeriod("year");
              setOffset(0);
            }}
          >
            <Text
              style={{
                color: period === "year" ? "#FFF" : colors.text,
                fontWeight: "600",
              }}
            >
              Yearly
            </Text>
          </TouchableOpacity>
        </View>

        {/* Period Navigator + Share */}
        <View style={[styles.navRow, { justifyContent: "space-between" }]}>
          <TouchableOpacity
            onPress={() => setOffset((o) => o + 1)}
            style={styles.navBtn}
          >
            <Ionicons name="chevron-back" size={22} color={colors.text} />
          </TouchableOpacity>
          <Text style={[styles.navLabel, { color: colors.text }]}>
            {periodLabel}
          </Text>
          <TouchableOpacity
            onPress={() => setOffset((o) => Math.max(0, o - 1))}
            style={styles.navBtn}
            disabled={offset === 0}
          >
            <Ionicons
              name="chevron-forward"
              size={22}
              color={offset === 0 ? colors.border : colors.text}
            />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={handleShareReport}
            style={[
              styles.navBtn,
              {
                backgroundColor: colors.primary + "15",
                borderRadius: 8,
                paddingHorizontal: 10,
              },
            ]}
          >
            <Ionicons name="share-outline" size={20} color={colors.primary} />
          </TouchableOpacity>
        </View>

        {/* Summary Cards */}
        <View style={styles.summaryGrid}>
          <Card style={styles.summaryCard}>
            <Text style={[styles.summaryLabel, { color: colors.textLight }]}>
              Income
            </Text>
            <AnimatedNumber
              value={curIncome}
              formatter={(v) => formatCurrency(v, currency)}
              style={{ ...styles.summaryValue, color: colors.success }}
            />
            {prevIncome > 0 && <ChangeIndicator value={incomeChange} />}
          </Card>
          <Card style={styles.summaryCard}>
            <Text style={[styles.summaryLabel, { color: colors.textLight }]}>
              Expenses
            </Text>
            <AnimatedNumber
              value={curSpent}
              formatter={(v) => formatCurrency(v, currency)}
              style={{ ...styles.summaryValue, color: colors.error }}
            />
            {prevSpent > 0 && <ChangeIndicator value={spentChange} inverted />}
          </Card>
        </View>

        {/* Net Balance */}
        <Card style={styles.netCard}>
          <View style={styles.netRow}>
            <View>
              <Text style={[styles.netLabel, { color: colors.textLight }]}>
                Net Balance
              </Text>
              <AnimatedNumber
                value={curBalance}
                formatter={(v) => formatCurrency(v, currency)}
                style={{
                  ...styles.netValue,
                  color: curBalance >= 0 ? colors.success : colors.error,
                }}
              />
            </View>
            {curIncome > 0 && (
              <View
                style={[
                  styles.savingsRateBox,
                  { backgroundColor: colors.primary + "15" },
                ]}
              >
                <Text
                  style={[styles.savingsRateNum, { color: colors.primary }]}
                >
                  {((curBalance / curIncome) * 100).toFixed(0)}%
                </Text>
                <Text
                  style={[styles.savingsRateLabel, { color: colors.primary }]}
                >
                  savings rate
                </Text>
              </View>
            )}
          </View>
        </Card>

        {/* Category Breakdown with Comparison */}
        <Card style={styles.sectionCard}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>
            Top Categories
          </Text>
          {curBreakdown.length > 0 ? (
            curBreakdown.slice(0, 5).map((item) => {
              const prevItem = prevBreakdown.find(
                (p) => p.category.id === item.category.id,
              );
              const change =
                prevItem && prevItem.amount > 0
                  ? ((item.amount - prevItem.amount) / prevItem.amount) * 100
                  : 0;
              const maxAmount = curBreakdown[0]?.amount || 1;
              return (
                <View key={item.category.id} style={styles.catRow}>
                  <View style={styles.catLeft}>
                    <View
                      style={[
                        styles.catIcon,
                        { backgroundColor: item.category.color + "15" },
                      ]}
                    >
                      <Icon
                        name={item.category.icon as any}
                        size={18}
                        color={item.category.color}
                      />
                    </View>
                    <View style={styles.catInfo}>
                      <View style={styles.catNameRow}>
                        <Text
                          style={[styles.catName, { color: colors.text }]}
                          numberOfLines={1}
                        >
                          {item.category.name}
                        </Text>
                        {Math.abs(change) >= 5 && (
                          <View
                            style={[
                              styles.catChange,
                              {
                                backgroundColor:
                                  change < 0
                                    ? colors.success + "15"
                                    : colors.error + "15",
                              },
                            ]}
                          >
                            <Ionicons
                              name={change < 0 ? "arrow-down" : "arrow-up"}
                              size={10}
                              color={change < 0 ? colors.success : colors.error}
                            />
                            <Text
                              style={{
                                fontSize: 10,
                                color:
                                  change < 0 ? colors.success : colors.error,
                                fontWeight: "600",
                              }}
                            >
                              {Math.abs(change).toFixed(0)}%
                            </Text>
                          </View>
                        )}
                      </View>
                      <View
                        style={[
                          styles.catBar,
                          { backgroundColor: colors.border },
                        ]}
                      >
                        <View
                          style={[
                            styles.catBarFill,
                            {
                              width: `${(item.amount / maxAmount) * 100}%`,
                              backgroundColor: item.category.color,
                            },
                          ]}
                        />
                      </View>
                    </View>
                  </View>
                  <View style={styles.catRight}>
                    <Text style={[styles.catAmount, { color: colors.text }]}>
                      {formatCurrency(item.amount, currency)}
                    </Text>
                    <Text
                      style={[styles.catPercent, { color: colors.textLight }]}
                    >
                      {item.percentage.toFixed(1)}%
                    </Text>
                  </View>
                </View>
              );
            })
          ) : (
            <View style={styles.emptySection}>
              <Ionicons
                name="pie-chart-outline"
                size={36}
                color={colors.textLight}
              />
              <Text style={[styles.emptyText, { color: colors.textLight }]}>
                No expenses this period
              </Text>
            </View>
          )}
        </Card>

        {/* Budget Status Summary */}
        {budgets.length > 0 && (
          <Card style={styles.sectionCard}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>
              Budget Status
            </Text>
            <View style={styles.budgetSummary}>
              <View style={styles.budgetStat}>
                <Text style={[styles.budgetStatNum, { color: colors.success }]}>
                  {
                    budgetStatuses.filter(
                      (b) => !b.isOverBudget && !b.isNearLimit,
                    ).length
                  }
                </Text>
                <Text
                  style={[styles.budgetStatLabel, { color: colors.textLight }]}
                >
                  On Track
                </Text>
              </View>
              <View
                style={[
                  styles.budgetDivider,
                  { backgroundColor: colors.border },
                ]}
              />
              <View style={styles.budgetStat}>
                <Text style={[styles.budgetStatNum, { color: colors.warning }]}>
                  {budgetStatuses.filter((b) => b.isNearLimit).length}
                </Text>
                <Text
                  style={[styles.budgetStatLabel, { color: colors.textLight }]}
                >
                  Near Limit
                </Text>
              </View>
              <View
                style={[
                  styles.budgetDivider,
                  { backgroundColor: colors.border },
                ]}
              />
              <View style={styles.budgetStat}>
                <Text style={[styles.budgetStatNum, { color: colors.error }]}>
                  {overBudgetCount}
                </Text>
                <Text
                  style={[styles.budgetStatLabel, { color: colors.textLight }]}
                >
                  Over Budget
                </Text>
              </View>
            </View>
          </Card>
        )}

        {/* Savings Goals Progress */}
        {savingsGoals.length > 0 && (
          <Card style={styles.sectionCard}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>
              Savings Progress
            </Text>
            <View style={styles.savingsOverview}>
              <Text style={[styles.savingsAmount, { color: colors.primary }]}>
                {formatCurrency(savingsTotal, currency)}
              </Text>
              <Text style={[styles.savingsTarget, { color: colors.textLight }]}>
                of {formatCurrency(savingsTarget, currency)} target
              </Text>
              <View
                style={[styles.savingsBar, { backgroundColor: colors.border }]}
              >
                <View
                  style={[
                    styles.savingsBarFill,
                    {
                      width: `${Math.min(100, savingsTarget > 0 ? (savingsTotal / savingsTarget) * 100 : 0)}%`,
                      backgroundColor: colors.primary,
                    },
                  ]}
                />
              </View>
            </View>
            {savingsGoals.map((goal) => {
              const pct =
                goal.targetAmount > 0
                  ? (goal.currentAmount / goal.targetAmount) * 100
                  : 0;
              return (
                <View key={goal.id} style={styles.goalRow}>
                  <View style={styles.goalInfo}>
                    <Text
                      style={[styles.goalName, { color: colors.text }]}
                      numberOfLines={1}
                    >
                      {goal.name}
                    </Text>
                    <Text style={[styles.goalPct, { color: colors.textLight }]}>
                      {pct.toFixed(0)}%
                    </Text>
                  </View>
                  <View
                    style={[styles.goalBar, { backgroundColor: colors.border }]}
                  >
                    <View
                      style={[
                        styles.goalBarFill,
                        {
                          width: `${Math.min(100, pct)}%`,
                          backgroundColor:
                            pct >= 100 ? colors.success : colors.primary,
                        },
                      ]}
                    />
                  </View>
                </View>
              );
            })}
          </Card>
        )}

        {/* Transaction Count */}
        <Card style={styles.sectionCard}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>
            Activity
          </Text>
          <View style={styles.activityRow}>
            <View style={styles.activityStat}>
              <Ionicons
                name="arrow-down-circle"
                size={24}
                color={colors.error}
              />
              <Text style={[styles.activityNum, { color: colors.text }]}>
                {curExpenses.length}
              </Text>
              <Text style={[styles.activityLabel, { color: colors.textLight }]}>
                Expenses
              </Text>
            </View>
            <View style={styles.activityStat}>
              <Ionicons
                name="arrow-up-circle"
                size={24}
                color={colors.success}
              />
              <Text style={[styles.activityNum, { color: colors.text }]}>
                {curIncomes.length}
              </Text>
              <Text style={[styles.activityLabel, { color: colors.textLight }]}>
                Income
              </Text>
            </View>
            <View style={styles.activityStat}>
              <Ionicons
                name="swap-horizontal"
                size={24}
                color={colors.primary}
              />
              <Text style={[styles.activityNum, { color: colors.text }]}>
                {curExpenses.length + curIncomes.length}
              </Text>
              <Text style={[styles.activityLabel, { color: colors.textLight }]}>
                Total
              </Text>
            </View>
          </View>
        </Card>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { padding: spacing.md, paddingBottom: spacing.xxl },
  periodRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  periodBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.lg,
    marginBottom: spacing.lg,
  },
  navBtn: { padding: spacing.xs },
  navLabel: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    minWidth: 160,
    textAlign: "center",
  },
  summaryGrid: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  summaryCard: {
    flex: 1,
    padding: spacing.md,
    alignItems: "center",
    gap: 4,
  },
  summaryLabel: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  summaryValue: {
    fontSize: typography.fontSize.xl,
    fontWeight: "700",
  },
  changeBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 2,
    marginTop: 2,
  },
  netCard: { padding: spacing.md, marginBottom: spacing.md },
  netRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  netLabel: {
    fontSize: typography.fontSize.sm,
    marginBottom: 4,
  },
  netValue: {
    fontSize: 28,
    fontWeight: "700",
  },
  savingsRateBox: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 12,
    alignItems: "center",
  },
  savingsRateNum: {
    fontSize: typography.fontSize.xl,
    fontWeight: "700",
  },
  savingsRateLabel: {
    fontSize: 10,
    fontWeight: "500",
  },
  sectionCard: {
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.bold,
    marginBottom: spacing.md,
  },
  catRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm + 2,
  },
  catLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  catIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  catInfo: { flex: 1 },
  catNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  catName: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  catChange: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 6,
    gap: 2,
  },
  catBar: {
    height: 6,
    borderRadius: 3,
    overflow: "hidden",
  },
  catBarFill: {
    height: "100%",
    borderRadius: 3,
  },
  catRight: {
    alignItems: "flex-end",
    marginLeft: spacing.sm,
  },
  catAmount: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
  },
  catPercent: {
    fontSize: 10,
  },
  emptySection: {
    alignItems: "center",
    paddingVertical: spacing.lg,
    gap: spacing.xs,
  },
  emptyText: { fontSize: typography.fontSize.sm },
  budgetSummary: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  budgetStat: { alignItems: "center", gap: 4 },
  budgetStatNum: {
    fontSize: typography.fontSize.xxl,
    fontWeight: "700",
  },
  budgetStatLabel: { fontSize: typography.fontSize.xs },
  budgetDivider: { width: 1, height: 40 },
  savingsOverview: {
    alignItems: "center",
    marginBottom: spacing.md,
    gap: 4,
  },
  savingsAmount: {
    fontSize: typography.fontSize.xl,
    fontWeight: "700",
  },
  savingsTarget: { fontSize: typography.fontSize.sm },
  savingsBar: {
    width: "100%",
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    marginTop: 8,
  },
  savingsBarFill: {
    height: "100%",
    borderRadius: 4,
  },
  goalRow: { marginBottom: spacing.sm },
  goalInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  goalName: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    flex: 1,
  },
  goalPct: { fontSize: typography.fontSize.xs },
  goalBar: {
    height: 6,
    borderRadius: 3,
    overflow: "hidden",
  },
  goalBarFill: { height: "100%", borderRadius: 3 },
  activityRow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  activityStat: { alignItems: "center", gap: 6 },
  activityNum: {
    fontSize: typography.fontSize.lg,
    fontWeight: "700",
  },
  activityLabel: { fontSize: typography.fontSize.xs },
});
